Import pandas

In [1]:
import pandas as pd

Load `escolas` dataframe from csv file.

In [2]:
escolas = pd.read_csv('data/escolas.csv')
escolas

id                               Escolas_Postos             BAIRRO  \
0    178  CENTRO INTEGRADO DE EDUCAÇÃO PÚBLICA HENFIL               CAJU   
1    634                   EM ALICE DO AMARAL PEIXOTO            BENFICA   
2    483                           EM CELESTINO SILVA             CENTRO   
3    476            ESCOLA MUNICIPAL FLORIANO PEIXOTO      SÃO CRISTÓVÃO   
4    132                            EM PEREIRA PASSOS       RIO COMPRIDO   
..   ...                                          ...                ...   
147  474                  EM ENGENHEIRO GASTÃO RANGEL          GUARATIBA   
148  301                           EM JONATAS SERRANO          GUARATIBA   
149  215                          E.M. NARCISA AMALIA  ILHA DE GUARATIBA   
150  606                        EM PROFESSOR CASTILHO  ILHA DE GUARATIBA   
151   69           ESCOLA MUNICIPAL CARDEAL ARCOVERDE          MADUREIRA   

                              ENDEREÇO          lat         lon  
0                 Rua Carlos Seidl S/Nº  -22,880888  -43,225326  
1                         Rua Ébano 187  -22,889574  -43,236202  
2                    R. do Lavradio, 56  -22,909293  -43,183579  
3                    Praça Argentina 20  -22,897629  -43,227456  
4    Praça Condessa Paulo de Frontin 45  -22,924412  -43,208579  
..                                  ...         ...         ...  
147            Estrada Do Magarça 9.183   -22,98046  -43,643545  
148          Estrada Do Mato Alto, S/Nº  -22,953163  -43,577409  
149  Estrada Teodoreto de Camargo S/N.º  -23,009084  -43,537582  
150              Caminho da Matriz 4406  -22,994124  -43,593683  
151          Rua Agostinho Barbalho 401  -22,876082  -43,343369  

[152 rows x 6 columns]

Rename `escolas` column names and set standard to snake case.

In [3]:
column_mapping = {
    'id': 'id',
    'Escolas_Postos': 'escolas_postos',
    'BAIRRO': 'bairro',
    'ENDEREÇO ': 'endereco',
    'lat': 'latitude',
    'lon': 'longitude'
}

escolas.rename(columns=column_mapping,inplace=True)
escolas['bairro'] = escolas['bairro'].str.title()

Replace `bairro` values from `escolas` dataframe with correct values from `subprefeituras` dataframe. 

In [4]:
bairros = {
'Humaita':'Humaitá', 
'Maracanã/ Vila Isabel':'Vila Isabel',
'Maracanã/ Tijuca':'Vila Isabel',
'Meier':'Méier', 
'Inhauma':'Inhaúma',
'Oswaldo Cruz':'Osvaldo Cruz',
'Gardenia Azul':'Gardênia Azul',
'Recreio':'Recreio Dos Bandeirantes',
'Rio Das Pedras':'Jacarepaguá',
'Freguesia Jpa': 'Freguesia (Jacarepaguá)',
'Augusto Vasconcelos':'Senador Vasconcelos',
'Paciencia':'Paciência',
'Nova Sepetiba': 'Sepetiba'
}

escolas['bairro'] = escolas['bairro'].replace(bairros)
escolas

id                               escolas_postos             bairro  \
0    178  CENTRO INTEGRADO DE EDUCAÇÃO PÚBLICA HENFIL               Caju   
1    634                   EM ALICE DO AMARAL PEIXOTO            Benfica   
2    483                           EM CELESTINO SILVA             Centro   
3    476            ESCOLA MUNICIPAL FLORIANO PEIXOTO      São Cristóvão   
4    132                            EM PEREIRA PASSOS       Rio Comprido   
..   ...                                          ...                ...   
147  474                  EM ENGENHEIRO GASTÃO RANGEL          Guaratiba   
148  301                           EM JONATAS SERRANO          Guaratiba   
149  215                          E.M. NARCISA AMALIA  Ilha De Guaratiba   
150  606                        EM PROFESSOR CASTILHO  Ilha De Guaratiba   
151   69           ESCOLA MUNICIPAL CARDEAL ARCOVERDE          Madureira   

                               endereco    latitude   longitude  
0                 Rua Carlos Seidl S/Nº  -22,880888  -43,225326  
1                         Rua Ébano 187  -22,889574  -43,236202  
2                    R. do Lavradio, 56  -22,909293  -43,183579  
3                    Praça Argentina 20  -22,897629  -43,227456  
4    Praça Condessa Paulo de Frontin 45  -22,924412  -43,208579  
..                                  ...         ...         ...  
147            Estrada Do Magarça 9.183   -22,98046  -43,643545  
148          Estrada Do Mato Alto, S/Nº  -22,953163  -43,577409  
149  Estrada Teodoreto de Camargo S/N.º  -23,009084  -43,537582  
150              Caminho da Matriz 4406  -22,994124  -43,593683  
151          Rua Agostinho Barbalho 401  -22,876082  -43,343369  

[152 rows x 6 columns]

Search for duplicated records in `escolas` dataframe.

In [21]:
duplicates_mask = escolas.duplicated(subset='id',keep=False)
duplicates_df = escolas[duplicates_mask]
duplicates_df.sort_values('id')

id                      escolas_postos           bairro  \
5     17        E.M PRESIDENTE JOSE LINHARES          Ipanema   
20    17        E.M PRESIDENTE JOSE LINHARES          Ipanema   
135   69  ESCOLA MUNICIPAL CARDEAL ARCOVERDE        Madureira   
80    69  ESCOLA MUNICIPAL CARDEAL ARCOVERDE        Madureira   
143   69  ESCOLA MUNICIPAL CARDEAL ARCOVERDE        Madureira   
69    69  ESCOLA MUNICIPAL CARDEAL ARCOVERDE        Madureira   
151   69  ESCOLA MUNICIPAL CARDEAL ARCOVERDE        Madureira   
9     89                    EM MARIO CLAUDIO     Rio Comprido   
57    89                    EM MARIO CLAUDIO     Rio Comprido   
25    89                    EM MARIO CLAUDIO     Rio Comprido   
84    89                    EM MARIO CLAUDIO     Rio Comprido   
70    90                 EM THOMAS JEFFERSON            Acari   
78    90                 EM THOMAS JEFFERSON            Acari   
117  206                         EM HONDURAS       Praça Seca   
99   206                         EM HONDURAS       Praça Seca   
56   379                 CIEP NELSON MANDELA     Campo Grande   
123  379                 CIEP NELSON MANDELA     Campo Grande   
112  379                 CIEP NELSON MANDELA     Campo Grande   
49   388                   EM CARDEAL CAMARA  Parada De Lucas   
60   388                   EM CARDEAL CAMARA  Parada De Lucas   
14   413                   EM CÓCIO BARCELOS       Copacabana   
15   413                   EM CÓCIO BARCELOS       Copacabana   
85   520             EM BARONESA DE SAAVEDRA         Realengo   
109  520             EM BARONESA DE SAAVEDRA         Realengo   
40   660        E.M NOSSA SENHORA DA POMPÉIA  Todos Os Santos   
34   660        E.M NOSSA SENHORA DA POMPÉIA  Todos Os Santos   

                                      endereco    latitude   longitude  
5                        R. Barão da Torre, 90  -22,983332  -43,199036  
20                       R. Barão da Torre, 90  -22,983332  -43,199036  
135                 Rua Agostinho Barbalho 401  -22,876082  -43,343369  
80                  Rua Agostinho Barbalho 401  -22,876082  -43,343369  
143                 Rua Agostinho Barbalho 401  -22,876082  -43,343369  
69                  Rua Agostinho Barbalho 401  -22,876082  -43,343369  
151                 Rua Agostinho Barbalho 401  -22,876082  -43,343369  
9                         R. Haddock Lobo, 148  -22,917233  -43,211044  
57                        R. Haddock Lobo, 148  -22,917233  -43,211044  
25                        R. Haddock Lobo, 148  -22,917233  -43,211044  
84                        R. Haddock Lobo, 148  -22,917233  -43,211044  
70   Avenida Pastor Martin Luther King Jr S/Nº   -22,81631  -43,340149  
78   Avenida Pastor Martin Luther King Jr S/Nº   -22,81631  -43,340149  
117                  Praça Barão da Taquara 12   -22896931   -43352667  
99                   Praça Barão da Taquara 12  -22,896931  -43,352667  
56                     Praça Daniel Lames, S/N  -22,895575  -43,570508  
123                   Praça Daniel Lames, S/Nº  -22,895575  -43,570508  
112                   Praça Daniel Lames, S/Nº  -22,895575  -43,570508  
49                                R. Anamá, 98   -22,81527  -43,303566  
60                                R. Anamá, 98   -22,81527  -43,303566  
14                     R. Barão de Ipanema, 34  -22,974828  -43,189063  
15                     R. Barão de Ipanema, 34   -22,74828  -43,189063  
85           R. Mal. Bibiano Costalat, 483-639   -22,87185  -43,432432  
109          R. Mal. Bibiano Costalat, 483-639   -22,87185  -43,432432  
40                          R. Cirne Maia, 109  -22,892031  -43,279925  
34                          R. Cirne Maia, 109  -22,892031  -43,279925

Drop duplicated records from `escolas` dataframe.
Indexes 117, 112 and 15 were not dropped since they contained slightly differences between the duplicated records, such as the lack of a comma, the presence of a special character and a typo, fas follows:

* 117	206	EM HONDURAS - sem vírgula na latitude e longitude
* 112	379	CIEP NELSON MANDELA - º no endereço
* 15	413	EM CÓCIO BARCELOS - latitude incompleta

In [6]:
escolas_unique = escolas.drop_duplicates()
# duplicates_mask = escolas_unique.duplicated(subset='id',keep=False)
# duplicates_df = escolas_unique[duplicates_mask]
# duplicates_df.sort_values('id')
escolas_unique = escolas_unique.drop([117,112,15]) # elimina escolas duplicadas, mas com ligeira diferença no registro
# 117	206	EM HONDURAS - sem vírgula na latitude e longitude
# 112	379	CIEP NELSON MANDELA - º no endereço
# 15	413	EM CÓCIO BARCELOS - latitude incompleta
escolas_unique

id                               escolas_postos              bairro  \
0    178  CENTRO INTEGRADO DE EDUCAÇÃO PÚBLICA HENFIL                Caju   
1    634                   EM ALICE DO AMARAL PEIXOTO             Benfica   
2    483                           EM CELESTINO SILVA              Centro   
3    476            ESCOLA MUNICIPAL FLORIANO PEIXOTO       São Cristóvão   
4    132                            EM PEREIRA PASSOS        Rio Comprido   
..   ...                                          ...                 ...   
146  210                   EM DEBORA MENDES DE MORAES  Pedra De Guaratiba   
147  474                  EM ENGENHEIRO GASTÃO RANGEL           Guaratiba   
148  301                           EM JONATAS SERRANO           Guaratiba   
149  215                          E.M. NARCISA AMALIA   Ilha De Guaratiba   
150  606                        EM PROFESSOR CASTILHO   Ilha De Guaratiba   

                               endereco    latitude   longitude  
0                 Rua Carlos Seidl S/Nº  -22,880888  -43,225326  
1                         Rua Ébano 187  -22,889574  -43,236202  
2                    R. do Lavradio, 56  -22,909293  -43,183579  
3                    Praça Argentina 20  -22,897629  -43,227456  
4    Praça Condessa Paulo de Frontin 45  -22,924412  -43,208579  
..                                  ...         ...         ...  
146         Rua Belchior Da Fonseca 643  -23,001416  -43,638757  
147            Estrada Do Magarça 9.183   -22,98046  -43,643545  
148          Estrada Do Mato Alto, S/Nº  -22,953163  -43,577409  
149  Estrada Teodoreto de Camargo S/N.º  -23,009084  -43,537582  
150              Caminho da Matriz 4406  -22,994124  -43,593683  

[136 rows x 6 columns]

In [7]:
material_didatico = pd.read_csv('data/material_didatico.csv')

column_mapping = {
    'id': 'id',
    'Quantidade': 'quantidade'
}

material_didatico.rename(columns=column_mapping,inplace=True)
material_didatico

id quantidade
0    178         20
1    634        121
2    483        220
3    476        190
4    132         67
..   ...        ...
146  474        320
147  301        335
148  215        NaN
149  606        521
150  590        225

[151 rows x 2 columns]

In [8]:
duplicates_mask = material_didatico.duplicated(subset='id',keep=False)
duplicates_df = material_didatico[duplicates_mask]
duplicates_df.sort_values('id')

Empty DataFrame
Columns: [id, quantidade]
Index: []

In [9]:
subprefeituras = pd.read_csv('data/subprefeituras.csv')

column_mapping = {
    'nome': 'bairro',
    'subprefeitura': 'subprefeitura'
}

subprefeituras.rename(columns=column_mapping,inplace=True)
subprefeituras['bairro'] = subprefeituras['bairro'].str.title()
subprefeituras

bairro subprefeitura
0          Santo Cristo        Centro
1                Gamboa        Centro
2                 Saúde        Centro
3                  Caju        Centro
4                Centro        Centro
..                  ...           ...
159          Santa Cruz    Zona Oeste
160           Guaratiba    Zona Oeste
161  Barra De Guaratiba    Zona Oeste
162  Pedra De Guaratiba    Zona Oeste
163   Ilha De Guaratiba    Zona Oeste

[164 rows x 2 columns]

In [10]:
duplicates_mask = subprefeituras.duplicated(subset='bairro',keep=False)
duplicates_df = subprefeituras[duplicates_mask]
duplicates_df.sort_values('bairro')

Empty DataFrame
Columns: [bairro, subprefeitura]
Index: []

In [11]:
df_temp = pd.merge(escolas_unique,material_didatico,on='id', how='left')

df_temp

id                               escolas_postos              bairro  \
0    178  CENTRO INTEGRADO DE EDUCAÇÃO PÚBLICA HENFIL                Caju   
1    634                   EM ALICE DO AMARAL PEIXOTO             Benfica   
2    483                           EM CELESTINO SILVA              Centro   
3    476            ESCOLA MUNICIPAL FLORIANO PEIXOTO       São Cristóvão   
4    132                            EM PEREIRA PASSOS        Rio Comprido   
..   ...                                          ...                 ...   
131  210                   EM DEBORA MENDES DE MORAES  Pedra De Guaratiba   
132  474                  EM ENGENHEIRO GASTÃO RANGEL           Guaratiba   
133  301                           EM JONATAS SERRANO           Guaratiba   
134  215                          E.M. NARCISA AMALIA   Ilha De Guaratiba   
135  606                        EM PROFESSOR CASTILHO   Ilha De Guaratiba   

                               endereco    latitude   longitude quantidade  
0                 Rua Carlos Seidl S/Nº  -22,880888  -43,225326         20  
1                         Rua Ébano 187  -22,889574  -43,236202        121  
2                    R. do Lavradio, 56  -22,909293  -43,183579        220  
3                    Praça Argentina 20  -22,897629  -43,227456        190  
4    Praça Condessa Paulo de Frontin 45  -22,924412  -43,208579         67  
..                                  ...         ...         ...        ...  
131         Rua Belchior Da Fonseca 643  -23,001416  -43,638757        570  
132            Estrada Do Magarça 9.183   -22,98046  -43,643545        320  
133          Estrada Do Mato Alto, S/Nº  -22,953163  -43,577409        335  
134  Estrada Teodoreto de Camargo S/N.º  -23,009084  -43,537582        NaN  
135              Caminho da Matriz 4406  -22,994124  -43,593683        521  

[136 rows x 7 columns]

In [12]:
df_final = pd.merge(df_temp,subprefeituras,on='bairro',how='left')

df_final

id                               escolas_postos              bairro  \
0    178  CENTRO INTEGRADO DE EDUCAÇÃO PÚBLICA HENFIL                Caju   
1    634                   EM ALICE DO AMARAL PEIXOTO             Benfica   
2    483                           EM CELESTINO SILVA              Centro   
3    476            ESCOLA MUNICIPAL FLORIANO PEIXOTO       São Cristóvão   
4    132                            EM PEREIRA PASSOS        Rio Comprido   
..   ...                                          ...                 ...   
131  210                   EM DEBORA MENDES DE MORAES  Pedra De Guaratiba   
132  474                  EM ENGENHEIRO GASTÃO RANGEL           Guaratiba   
133  301                           EM JONATAS SERRANO           Guaratiba   
134  215                          E.M. NARCISA AMALIA   Ilha De Guaratiba   
135  606                        EM PROFESSOR CASTILHO   Ilha De Guaratiba   

                               endereco    latitude   longitude quantidade  \
0                 Rua Carlos Seidl S/Nº  -22,880888  -43,225326         20   
1                         Rua Ébano 187  -22,889574  -43,236202        121   
2                    R. do Lavradio, 56  -22,909293  -43,183579        220   
3                    Praça Argentina 20  -22,897629  -43,227456        190   
4    Praça Condessa Paulo de Frontin 45  -22,924412  -43,208579         67   
..                                  ...         ...         ...        ...   
131         Rua Belchior Da Fonseca 643  -23,001416  -43,638757        570   
132            Estrada Do Magarça 9.183   -22,98046  -43,643545        320   
133          Estrada Do Mato Alto, S/Nº  -22,953163  -43,577409        335   
134  Estrada Teodoreto de Camargo S/N.º  -23,009084  -43,537582        NaN   
135              Caminho da Matriz 4406  -22,994124  -43,593683        521   

    subprefeitura  
0          Centro  
1          Centro  
2          Centro  
3          Centro  
4          Centro  
..            ...  
131    Zona Oeste  
132    Zona Oeste  
133    Zona Oeste  
134    Zona Oeste  
135    Zona Oeste  

[136 rows x 8 columns]

In [19]:
df_final.describe()

id
count  136.000000
mean   356.514706
std    199.858727
min     11.000000
25%    179.500000
50%    367.000000
75%    529.500000
max    690.000000

In [14]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   id              136 non-null    int64 
 1   escolas_postos  136 non-null    object
 2   bairro          136 non-null    object
 3   endereco        136 non-null    object
 4   latitude        136 non-null    object
 5   longitude       136 non-null    object
 6   quantidade      132 non-null    object
 7   subprefeitura   136 non-null    object
dtypes: int64(1), object(7)
memory usage: 8.6+ KB


In [15]:
df_final[df_final['subprefeitura'].isnull()]

Empty DataFrame
Columns: [id, escolas_postos, bairro, endereco, latitude, longitude, quantidade, subprefeitura]
Index: []

In [20]:
qt_mask = pd.to_numeric(df_final['quantidade'], errors='coerce').isna()
not_numeric = df_final[qt_mask]
not_numeric

id                         escolas_postos                   bairro  \
14   413                      EM CÓCIO BARCELOS               Copacabana   
28    60   ESCOLA MUNICIPAL BARÃO HOMEM DE MELO              Vila Isabel   
35   429                       EM FELIX PACHECO                  Piedade   
62   260           EM PROFESSOR JOSUE DE CASTRO               Bonsucesso   
71    91                             E.M. PIAUI                Guadalupe   
77   412                         EM MOZART LAGO             Osvaldo Cruz   
91   492                      EM MENEZES CORTES  Freguesia (Jacarepaguá)   
106  687                   EM TASSO DA SILVEIRA                 Realengo   
127  297  EM PROFESSORA SILVIA DE ARAUJO TOLEDO               Santa Cruz   
134  215                    E.M. NARCISA AMALIA        Ilha De Guaratiba   

                                  endereco    latitude   longitude quantidade  \
14                 R. Barão de Ipanema, 34  -22,974828  -43,189063         ''   
28        R. Alm. João Cândido Brasil, 352  -22,916829  -43,236925      'NaN'   
35                  R. Assis Carneiro, 649  -22,895086  -43,313826        NaN   
62          Av. Brasil 4040 Rua da Vitória  -22,873739  -43,240712      '397'   
71                   Avenida Brasil 23.364  -22,845415   -43,37852      'NaN'   
77         Rua José Carvalho Salgado S/N.º  -22,872211  -43,350334      '395'   
91          Praça José Alves De Azevedo 43  -22,942655  -43,338969        NaN   
106  Rua General Bernardino de Matos S/N.º  -22,883859   -43,41733        NaN   
127    Avenida Canal 3 S/N.º Conj. Cesarão  -22,930111  -43,652899        ' '   
134     Estrada Teodoreto de Camargo S/N.º  -23,009084  -43,537582        NaN   

     subprefeitura  
14        Zona Sul  
28   Grande Tijuca  
35      Zona Norte  
62      Zona Norte  
71      Zona Norte  
77      Zona Norte  
91     Jacarepaguá  
106   Grande Bangu  
127     Zona Oeste  
134     Zona Oeste

In [17]:
subprefeituras_lst = list(subprefeituras['bairro'].unique())
subprefeituras_lst.sort()
subprefeituras_lst

['Abolição',
 'Acari',
 'Alto Da Boa Vista',
 'Anchieta',
 'Andaraí',
 'Anil',
 'Bancários',
 'Bangu',
 'Barra Da Tijuca',
 'Barra De Guaratiba',
 'Barros Filho',
 'Benfica',
 'Bento Ribeiro',
 'Bonsucesso',
 'Botafogo',
 'Brás De Pina',
 'Cachambi',
 'Cacuia',
 'Caju',
 'Camorim',
 'Campinho',
 'Campo Dos Afonsos',
 'Campo Grande',
 'Cascadura',
 'Catete',
 'Catumbi',
 'Cavalcanti',
 'Centro',
 'Cidade De Deus',
 'Cidade Nova',
 'Cidade Universitária',
 'Cocotá',
 'Coelho Neto',
 'Colégio',
 'Complexo Do Alemão',
 'Copacabana',
 'Cordovil',
 'Cosme Velho',
 'Cosmos',
 'Costa Barros',
 'Curicica',
 'Del Castilho',
 'Deodoro',
 'Encantado',
 'Engenheiro Leal',
 'Engenho Da Rainha',
 'Engenho De Dentro',
 'Engenho Novo',
 'Estácio',
 'Flamengo',
 'Freguesia (Ilha)',
 'Freguesia (Jacarepaguá)',
 'Galeão',
 'Gamboa',
 'Gardênia Azul',
 'Gericinó',
 'Glória',
 'Grajaú',
 'Grumari',
 'Guadalupe',
 'Guaratiba',
 'Gávea',
 'Higienópolis',
 'Honório Gurgel',
 'Humaitá',
 'Ilha De Guaratiba',
 '